name: Merge All Contributors

on:
  workflow_call:
  workflow_dispatch:

jobs:
  merge-contributors:
    runs-on: ubuntu-latest
    permissions:
       contents: write
       pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: the-turing-way/all-all-contributors@feat/generate-table
        with:
          organisation: ${{ github.repository_owner }}
          target_repo: ${{ github.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head_branch: table-test
