name: Merge All Contributors

on:
  push:
    paths:
      - ".all-contributorsrc"
  workflow_call:
  workflow_dispatch:

jobs:
  merge-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: the-turing-way/all-all-contributors@main
        with:
          organisation: sgibson91-test-org
          target_repo: .github

